version: '3.9'

services:
  php: &php-template
    build:
      context: ./
      dockerfile: Dockerfile
    image: php83:latest
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    working_dir: '/var/www/html'
    env_file:
      - "./.env"
    environment:
      - "DB_HOST=mysql"
      - "MEMCACHED_HOST=memcached"
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - "./public:/var/www/html/public"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "8080:80"
    depends_on:
      - php
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 222222
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: 111111
    volumes:
      - db:/var/lib/mysql
  memcached:
    image: sameersbn/memcached:1.5.6-2
    restart: unless-stopped

volumes:
  db:
    driver: local
