version: '3.9'

services:
  php: &php-template
    build: .
    image: php82:latest
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    working_dir: '/var/www/html'
    env_file:
      - "./.env"
    environment:
      - "DB_HOST=mysql"
      - "MEMCACHED_HOST=memcached"
    depends_on:
      mysql:
        condition: service_healthy
  queue:
    <<: *php-template
    restart: unless-stopped
    command: "php artisan queue:work"
  migrate:
    <<: *php-template
    restart: no
    command: "php artisan migrate"
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - "./public:/var/www/html/public"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "8080:80"
    depends_on:
      - php
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 222222
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: 111111
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  memcached:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - "11211:11211"
    restart: unless-stopped

volumes:
  db:
    driver: local
